### ISSUE TITLE
Travel Lengths off in a new way

### ISSUE THREAD

**Issue by rizen** [rizen/SVG-Estimate#10]
When I run this through SVG estimate it gives me the following output:

Total Length: 2828px 39.276in
    Shape Length: 1585px 22.019in
    Travel Length: 1243px 17.257in
    Shapes: 8
    Width: 205px 2.852in
    Height: 352px 4.901in

However, by just eyeballing it in Illustrator, the travel length should be: 

2.11 + 0.01 + 0.01 + 0.01 + 0.968 + 0.01 + 0.4715 = 3.5795 inches

The shape length appears to be roughly correct.

[firstplayer.svg.zip](https://github.com/rizen/SVG-Estimate/files/429464/firstplayer.svg.zip)

**Comment by perlDreamer** [comment]
Fixed this in SVG::Estimate 1.0101
