### ISSUE TITLE
wrong width and height

### ISSUE THREAD

**Issue by rizen** [rizen/SVG-Estimate#9]
This file causes all kinds of uninitialization warnings

Use of uninitialized value in addition (+) at ../lib/SVG/Estimate/Path/Arc.pm line 197.
Use of uninitialized value in addition (+) at ../lib/SVG/Estimate/Path/Arc.pm line 197.
Use of uninitialized value in subtraction (-) at ../lib/SVG/Estimate/Path/Arc.pm line 171.
Use of uninitialized value in subtraction (-) at ../lib/SVG/Estimate/Path/Arc.pm line 172.
Use of uninitialized value in addition (+) at ../lib/SVG/Estimate/Path/Arc.pm line 197.
Use of uninitialized value in addition (+) at ../lib/SVG/Estimate/Path/Arc.pm line 197.
Use of uninitialized value in subtraction (-) at ../lib/SVG/Estimate/Path/Arc.pm line 171.
Use of uninitialized value in subtraction (-) at ../lib/SVG/Estimate/Path/Arc.pm line 172.
Use of uninitialized value in addition (+) at ../lib/SVG/Estimate/Path/Arc.pm line 197.
Use of uninitialized value in addition (+) at ../lib/SVG/Estimate/Path/Arc.pm line 197.

And also results in a wrong size being reported. It should be somewhere around 3.25 x 5.25 inches, but it reports 12.232 x 8.365in.

[playerPieces.svg.zip](https://github.com/rizen/SVG-Estimate/files/398264/playerPieces.svg.zip)

**Comment by perlDreamer** [comment]
This was due to the parameters for Arc not being like Bezier, Cubic and Quadratic.
